qualifications = [
  "Associate",
  "Bachelor's (B.A.)",
  "Bachelor's (B.Sc.)",
  "Bachelor's (B.Com.)",
  "Bachelor's (B.Eng.)",
  "Bachelor's (B.Ed.)",
  "Bachelor's (LLB)",
  "Diploma",
  "Graduate Certificate",
  "Graduate Diploma",
  "High School (S.S.C.E)",
  "HND",
  "Master's (M.A.)",
  "Master's (M.Sc.)",
  "Master's (M.Com.)",
  "Master's (M.Eng.)",
  "Master's (M.Ed.)",
  "MBA",
  "MBBS",
  "MPhil",
  "N.C.E",
  "OND",
  "PhD",
  "Postgraduate Certificate",
  "Postgraduate Diploma",
  "Professional Certificate",
  "Technical Certificate",
  "Vocational",
]

experienceLevels = [
  "No Experience",
  "1 year",
  "2 years",
  "3 years",
  "4 years",
  "5 years",
  "6 years",
  "7 years",
  "8 years",
  "9 years",
  "10 years",
  "11 years",
  "12 years",
  "13 years",
  "14 years",
  "15 years",
  "16 years",
  "17 years",
  "18 years",
  "19 years",
  "20 years",
  "> 20 years",
  "Highly Experienced"
]

workPatterns = [
  "Full Time",
  "Part Time",
  "Contract",
  "Temporary",
  "Freelance",
  "On Site",
  "Remote",
  "Hybrid"
]

jobSalary_default = "Undisclosed"
