qualifications = [
    "Associate",
    "Bachelor's (B.A.)",
    "Bachelor's (B.Sc.)",
    "Bachelor's (B.Com.)",
    "Bachelor's (B.Eng.)",
    "Bachelor's (B.Ed.)",
    "Bachelor's (LLB)",
    "Diploma",
    "Graduate Certificate",
    "Graduate Diploma",
    "High School (S.S.C.E)",
    "HND",
    "Master's (M.A.)",
    "Master's (M.Sc.)",
    "Master's (M.Com.)",
    "Master's (M.Eng.)",
    "Master's (M.Ed.)",
    "MBA",
    "MBBS",
    "MPhil",
    "N.C.E",
    "OND",
    "PhD",
    "Postgraduate Certificate",
    "Postgraduate Diploma",
    "Professional Certificate",
    "Technical Certificate",
    "Vocational",
]

experienceLevels = [
    "No Experience",
    "1 year",
    "2 years",
    "3 years",
    "4 years",
    "5 years",
    "6 years",
    "7 years",
    "8 years",
    "9 years",
    "10 years",
    "11 years",
    "12 years",
    "13 years",
    "14 years",
    "15 years",
    "16 years",
    "17 years",
    "18 years",
    "19 years",
    "20 years",
    "> 20 years",
    "Highly Experienced",
]

workPatterns = [
    "Full Time",
    "Part Time",
    "Contract",
    "Temporary",
    "Freelance",
    "On Site",
    "Remote",
    "Hybrid",
]

jobSalary_default = "Undisclosed"

CAPITALS = {
    "kabul": "AF",
    "tirana": "AL",
    "algiers": "DZ",
    "andorra la vella": "AD",
    "luanda": "AO",
    "buenos aires": "AR",
    "yerevan": "AM",
    "canberra": "AU",
    "vienna": "AT",
    "baku": "AZ",
    "nassau": "BS",
    "manama": "BH",
    "dhaka": "BD",
    "bridgetown": "BB",
    "minsk": "BY",
    "brussels": "BE",
    "belmopan": "BZ",
    "porto-novo": "BJ",
    "thimphu": "BT",
    "la paz": "BO",
    "sarajevo": "BA",
    "gaborone": "BW",
    "brasília": "BR",
    "bandar seri begawan": "BN",
    "sofia": "BG",
    "ouagadougou": "BF",
    "bujumbura": "BI",
    "phnom penh": "KH",
    "yaoundé": "CM",
    "ottawa": "CA",
    "praia": "CV",
    "bangui": "CF",
    "n'djamena": "TD",
    "santiago": "CL",
    "beijing": "CN",
    "bogotá": "CO",
    "moroni": "KM",
    "kinshasa": "CD",
    "brazzaville": "CG",
    "san josé": "CR",
    "zagreb": "HR",
    "havana": "CU",
    "nicosia": "CY",
    "prague": "CZ",
    "copenhagen": "DK",
    "djibouti": "DJ",
    "roseau": "DM",
    "santo domingo": "DO",
    "quito": "EC",
    "cairo": "EG",
    "san salvador": "SV",
    "malabo": "GQ",
    "asmara": "ER",
    "tallinn": "EE",
    "addis ababa": "ET",
    "suva": "FJ",
    "helsinki": "FI",
    "paris": "FR",
    "libreville": "GA",
    "banjul": "GM",
    "tbilisi": "GE",
    "berlin": "DE",
    "accra": "GH",
    "athens": "GR",
    "guatemala city": "GT",
    "conakry": "GN",
    "bissau": "GW",
    "georgetown": "GY",
    "port-au-prince": "HT",
    "tegucigalpa": "HN",
    "budapest": "HU",
    "reykjavik": "IS",
    "new delhi": "IN",
    "jakarta": "ID",
    "tehran": "IR",
    "baghdad": "IQ",
    "dublin": "IE",
    "jerusalem": "IL",
    "rome": "IT",
    "kingston": "JM",
    "tokyo": "JP",
    "amman": "JO",
    "nur-sultan": "KZ",
    "nairobi": "KE",
    "tarawa": "KI",
    "pyongyang": "KP",
    "seoul": "KR",
    "pristina": "XK",
    "kuwait city": "KW",
    "bishkek": "KG",
    "vientiane": "LA",
    "riga": "LV",
    "beirut": "LB",
    "maseru": "LS",
    "monrovia": "LR",
    "tripoli": "LY",
    "vaduz": "LI",
    "vilnius": "LT",
    "luxembourg": "LU",
    "skopje": "MK",
    "antananarivo": "MG",
    "lilongwe": "MW",
    "kuala lumpur": "MY",
    "malé": "MV",
    "bamako": "ML",
    "valletta": "MT",
    "majuro": "MH",
    "nouakchott": "MR",
    "port louis": "MU",
    "mexico city": "MX",
    "palikir": "FM",
    "chișinău": "MD",
    "monaco": "MC",
    "ulaanbaatar": "MN",
    "podgorica": "ME",
    "rabat": "MA",
    "maputo": "MZ",
    "naypyidaw": "MM",
    "windhoek": "NA",
    "kathmandu": "NP",
    "amsterdam": "NL",
    "wellington": "NZ",
    "managua": "NI",
    "niamey": "NE",
    "abuja": "NG",
    "oslo": "NO",
    "muscat": "OM",
    "islamabad": "PK",
    "ngerulmud": "PW",
    "panama city": "PA",
    "port moresby": "PG",
    "asunción": "PY",
    "lima": "PE",
    "manila": "PH",
    "warsaw": "PL",
    "lisbon": "PT",
    "doha": "QA",
    "bucharest": "RO",
    "moscow": "RU",
    "kigali": "RW",
    "basseterre": "KN",
    "castries": "LC",
    "kingstown": "VC",
    "apia": "WS",
    "san marino": "SM",
    "são tomé": "ST",
    "riyadh": "SA",
    "dakar": "SN",
    "belgrade": "RS",
    "victoria": "SC",
    "freetown": "SL",
    "singapore": "SG",
    "bratislava": "SK",
    "ljubljana": "SI",
    "honiara": "SB",
    "mogadishu": "SO",
    "pretoria": "ZA",
    "juba": "SS",
    "madrid": "ES",
    "colombo": "LK",
    "khartoum": "SD",
    "paramaribo": "SR",
    "stockholm": "SE",
    "bern": "CH",
    "damascus": "SY",
    "taipei": "TW",
    "dushanbe": "TJ",
    "dodoma": "TZ",
    "bangkok": "TH",
    "dili": "TL",
    "lomé": "TG",
    "nuku'alofa": "TO",
    "port of spain": "TT",
    "tunis": "TN",
    "ankara": "TR",
    "ashgabat": "TM",
    "funafuti": "TV",
    "kampala": "UG",
    "kyiv": "UA",
    "abu dhabi": "AE",
    "london": "GB",
    "washington": "US",
    "montevideo": "UY",
    "tashkent": "UZ",
    "port vila": "VU",
    "vatican city": "VA",
    "caracas": "VE",
    "hanoi": "VN",
    "sana'a": "YE",
    "lusaka": "ZM",
    "harare": "ZW",
}
# All US States (full names and common abbreviations)
US_STATES = {
    "alabama": "US",
    "al": "US",
    "alaska": "US",
    "ak": "US",
    "arizona": "US",
    "az": "US",
    "arkansas": "US",
    "ar": "US",
    "california": "US",
    "ca": "US",
    "colorado": "US",
    "chicago": "US",
    "co": "US",
    "connecticut": "US",
    "ct": "US",
    "delaware": "US",
    "de": "US",
    "florida": "US",
    "fl": "US",
    "georgia": "US",
    "ga": "US",
    "hawaii": "US",
    "hi": "US",
    "idaho": "US",
    "id": "US",
    "illinois": "US",
    "il": "US",
    "indiana": "US",
    "in": "US",
    "iowa": "US",
    "ia": "US",
    "kansas": "US",
    "ks": "US",
    "kentucky": "US",
    "ky": "US",
    "louisiana": "US",
    "la": "US",
    "maine": "US",
    "me": "US",
    "maryland": "US",
    "md": "US",
    "massachusetts": "US",
    "ma": "US",
    "michigan": "US",
    "mi": "US",
    "minnesota": "US",
    "mn": "US",
    "mississippi": "US",
    "ms": "US",
    "missouri": "US",
    "mo": "US",
    "montana": "US",
    "mt": "US",
    "nebraska": "US",
    "ne": "US",
    "nevada": "US",
    "nv": "US",
    "new hampshire": "US",
    "nh": "US",
    "new jersey": "US",
    "nj": "US",
    "new mexico": "US",
    "nm": "US",
    "new york": "US",
    "ny": "US",
    "north carolina": "US",
    "nc": "US",
    "north dakota": "US",
    "nd": "US",
    "ohio": "US",
    "oh": "US",
    "oklahoma": "US",
    "ok": "US",
    "oregon": "US",
    "or": "US",
    "pennsylvania": "US",
    "pa": "US",
    "rhode island": "US",
    "ri": "US",
    "south carolina": "US",
    "sc": "US",
    "south dakota": "US",
    "sd": "US",
    "tennessee": "US",
    "tn": "US",
    "texas": "US",
    "tx": "US",
    "utah": "US",
    "ut": "US",
    "vermont": "US",
    "vt": "US",
    "virginia": "US",
    "va": "US",
    "washington": "US",
    "wa": "US",
    "west virginia": "US",
    "wv": "US",
    "wisconsin": "US",
    "wi": "US",
    "wyoming": "US",
    "wy": "US",
    # US Territories
    "puerto rico": "US",
    "pr": "US",
    "guam": "US",
    "gu": "US",
    "virgin islands": "US",
    "vi": "US",
    "american samoa": "US",
    "as": "US",
    "northern mariana islands": "US",
    "mp": "US",
    "district of columbia": "US",
    "dc": "US",
    "washington d.c.": "US",
    "washington dc": "US",
}
